server:
  port: 8765

spring:
  application:
    name: service-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream