server:
  port: 8000

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Novellatonyatt/config.git
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/