server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/

spring:
  application:
    name: service-gateway
  #  profiles:
  #    active: zht
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #使为eureka中的每一个服务创建一个router，以服务名开头的请求都会转发到对应的服务。
          lowerCaseServiceId: true

