#只要请求满足指定的path，则进入该route。
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8762
          predicates:
            - Path=/service-hi/{segment} # Path表示使用PathRoutePredicateFactory