#应用端口
server:
  port: 8760

#应用名称
spring:
  application:
    name: eurka-server-peer1

#eureka配置
eureka:
  instance:
    hostname: peer1 #eureka instance的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: #eureka的服务地址
      defaultZone: http://peer2:8761/eureka/

