server:
  port: 8763

spring:
  application:
    name: service-hi
  zipkin:  #指定zipKin server的地址
    baseUrl: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/
