server:
  port: 8764

spring:
  application:
    name: service-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

